#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by nimbus.llnl.gov - 2025/09/29 05:54:15
# Search URL: http://nimbus.llnl.gov/wget
# Request method: POST
# 
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://nimbus.llnl.gov/wget'
request_method='POST'
url_params=(
    'CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r15i1p1f1.Amon.prw.gr.v20200201|eagle.alcf.anl.gov'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186901-186912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186901-186912.nc' 'SHA256' '912cf849289f2610a42f8e8c5db15c88a7b6b7baa17b330e6cb60568b587f9b4'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190801-190812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190801-190812.nc' 'SHA256' 'c15bb60b51c01eeef7f7c2b1712dc18d6202d827a5849a7a1973b7a29276beb1'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191001-191012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191001-191012.nc' 'SHA256' '316ca1234c32d1b55108f0f63671eaf38c343ae8bc369b99285c7d13e44c38b1'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192101-192112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192101-192112.nc' 'SHA256' '189f8968a067e96525f1ff68359537a27306e239bcea99fd9b6bf21e2e251eb9'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192801-192812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192801-192812.nc' 'SHA256' 'b061b447e58c8cb9a4f62d2a203fec2aefc917c0ce2552f6461cf0dd1ecfa09a'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193101-193112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193101-193112.nc' 'SHA256' '2a97dc792abb6e265f981a14301c3e933cb9ac560ad90f0b14cbaf3fba38fc60'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194601-194612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194601-194612.nc' 'SHA256' 'bb6a562222d9714200d463bba6e81678833ec1d58dc5a13b0f981af8696ec7d5'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194701-194712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194701-194712.nc' 'SHA256' '16fdb1c5731af7ecb80576ccca1682855db520ce7db05213cf8213c17a2c79ab'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195401-195412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195401-195412.nc' 'SHA256' '43164895d1f2c22ad40ce2a5bcd179f38866f43f0704b6e5077aa9303c22696d'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196501-196512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196501-196512.nc' 'SHA256' '1729fc36e840a6e149b7f98cf98404225438a5b7e7581fac8c99edd11fe6d517'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197701-197712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197701-197712.nc' 'SHA256' 'de6375321184e2ea8b4899351f2be37aab7d78d52a8388676c89c2def219fd5c'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198401-198412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198401-198412.nc' 'SHA256' '5cdc014b77e184a6983a7906adc1388c993760ebb06e2e3fe3fe94651faf431a'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200001-200012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200001-200012.nc' 'SHA256' 'ffb70c06fc9174337c55361d0c983f3ee748ac6fb19021364e28cf8ff99242ab'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200801-200812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200801-200812.nc' 'SHA256' '5b46f8687223e78f44adf039fb0fc902673eaf555c377d0135ee38b1d9cdb424'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185501-185512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185501-185512.nc' 'SHA256' 'dae1ec99eb114780e01e679a762fe334e7668f612e01d81d77434c3ba8cfaaf5'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187301-187312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187301-187312.nc' 'SHA256' '0143ae243e2d256361ea08bd688f16d636b879cf2b7c1629023ee4460e09ae7f'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190401-190412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190401-190412.nc' 'SHA256' 'adc9d967cea1abf2abcc2d73fcb54ba92ea86b25ce48c5386ce995467c3bec87'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192701-192712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192701-192712.nc' 'SHA256' 'f1b05f8e56889fef1f751cdda62b324e646a9b0f1f9c79973f177981144af41a'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193301-193312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193301-193312.nc' 'SHA256' '28cdc83e7ae525ed0cc7972d988ffce6dd9a6c7677048b064cea8d6ad11cb54d'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193701-193712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193701-193712.nc' 'SHA256' '8dd96262828becfac812d76e73700dcb5a3388208af52bd0b31e94f39c5cdcf0'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195901-195912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195901-195912.nc' 'SHA256' 'c75f102be680db1c041359d40c223e5df11f266ada1fea0e881a69542dc4b74a'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199001-199012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199001-199012.nc' 'SHA256' '248a303709d8129be0c174b378fa1b388f8ee3c49ba5f59eed829375583e86a3'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200701-200712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200701-200712.nc' 'SHA256' 'c209689914f7d997f111ff8ac683ae4d180fd897c862f1447db21de1223b860b'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189501-189512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189501-189512.nc' 'SHA256' 'dd56771600d510c5cbf85555c8b20abd5a3570879266eeab4ec62e47ad3e4f3c'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190201-190212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190201-190212.nc' 'SHA256' '8766249cd4c3dc561c5e5b5cea24e26001a0e0e7a636dbffb16f3abe210f2555'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190301-190312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190301-190312.nc' 'SHA256' 'd6108aa2743b249b7065b530fbbb994e412cae460257d262f2c2cb0d1f8b9e50'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191501-191512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191501-191512.nc' 'SHA256' '00823f285ec7e74121638a61f094e4d22805817503d09b9370e1436124cf16a7'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192001-192012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192001-192012.nc' 'SHA256' '869aea92d95e8950c8933ba9f487a14f725281b9826f74c78e0fdd6ec8aa10c7'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194101-194112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194101-194112.nc' 'SHA256' '800b77b571be11924fb7fb1cf1d76fa4b8181f15b7931249d50c0d791c93b5c3'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194501-194512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194501-194512.nc' 'SHA256' '1d7305d3854689595c5de51bb5e47b7e58f7d6b60c7abbdd8687ca22f140310f'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194901-194912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194901-194912.nc' 'SHA256' '303f218dfbb454fea1fd7434605a5795acd3fba5f31af8fe6c5f6149e904385f'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196301-196312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196301-196312.nc' 'SHA256' '17413582337a61567d2226fa7a466255c407e50af394e47f3a038520d9f11627'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197001-197012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197001-197012.nc' 'SHA256' '5498c92aa252eb93f9099dc6fa6743029aaa1555d8dee5e869d2ae191bbea534'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200101-200112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200101-200112.nc' 'SHA256' '7579c7c3092bfd4eef51c8bda1d48630b747b959b1acfdc3185eb395ef23783b'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200501-200512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200501-200512.nc' 'SHA256' '7adb8eb825cb4611bffc00358a0fe043b3685aec4e2f6db3238ca8e975f80207'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185701-185712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185701-185712.nc' 'SHA256' 'aa55458bfe70da837b2bc4d6a6ca8976d6c2511f3aa495cbbc67903886d61f5f'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187801-187812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187801-187812.nc' 'SHA256' '1709235768b5f9cca7fbb574c83b81284d1ef9e52eb364e805806808040d9810'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191601-191612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191601-191612.nc' 'SHA256' 'a30d49cb8ef0676cd57ad00097323b53c83b30973694e0cbef4ccd6dde39db41'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191901-191912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191901-191912.nc' 'SHA256' '3d25701d401e1a97a4f363533af4101efde827fa0a1f9899653705c9dcd064f2'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192201-192212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192201-192212.nc' 'SHA256' '5751a9d6edfff2fe53b827586960ef40b9afab6302fbeaffbcbcf0b4e914c4c7'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193901-193912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193901-193912.nc' 'SHA256' '20fdfc0719f451356e7c4ab5000bf98a5e17fd0ce33b07a30520df60c045ad0a'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195001-195012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195001-195012.nc' 'SHA256' 'd003fef1ac0446d3bba8c58855ab975f9a154fc2c955f4d611227ffa2ef79f45'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196701-196712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196701-196712.nc' 'SHA256' 'd0e8c4644f64a35336673e76d49363a32d06914adebd6fc73523df099df65006'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200201-200212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200201-200212.nc' 'SHA256' 'c9fb80c9a23210c55af2a16ec84f16401917eb65e89aebab2ae2a4bcbac3e434'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186101-186112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186101-186112.nc' 'SHA256' 'd59342d09e37942d99379823d692c9bb96eb0f1827575461c25c870a90b3e199'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187401-187412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187401-187412.nc' 'SHA256' 'fb66b184db3cac96e1a8e9a4b314ed6855735b1ff07c20ee5274d1e9cefca254'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188501-188512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188501-188512.nc' 'SHA256' '8f463968b53a3fc1a94fababaad1d3c279deec1682ef29eaae5f90488de5e784'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190101-190112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190101-190112.nc' 'SHA256' 'aed595bb694193c4359d5a3bffa57f219f99f88b20396d71daf5d190467c860a'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190701-190712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190701-190712.nc' 'SHA256' '9dc20a097f65a66919acab89171d883f71e38bc34336071dcbbd179cf746b10c'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194201-194212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194201-194212.nc' 'SHA256' 'e34100e1622583e022dceb2b3e2a000def7df5f2f3d7de3ca2301c14d9fe59c4'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195101-195112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195101-195112.nc' 'SHA256' '6350b38d9d95b5f0efa7c4f614dc90bc1b5d39b9810a5904580da475e85adc49'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195301-195312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195301-195312.nc' 'SHA256' '7bcaf8f1ccef6dbf5cb341d48d433e3a632508f277ad2ab2970f790180bf840f'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196401-196412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196401-196412.nc' 'SHA256' 'fd21b9ac7eae0e2f9be84b98370f0d6b8a9c0022294f93b28a4de24b0aa174fd'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198201-198212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198201-198212.nc' 'SHA256' 'bdb43e2a57adc52d9bc8624582635ddf9c466d8c19d688c64b8cb9f1f37a74f5'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199201-199212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199201-199212.nc' 'SHA256' 'd49b2344ac4d8324fe601d89d9b83c4153e53f682fdc0a36139f5528cc441f13'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200301-200312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200301-200312.nc' 'SHA256' 'bc5ac16200bf57b33d9853aa82933a57cf11792c62c894b72c7130210f5f2885'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185901-185912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185901-185912.nc' 'SHA256' '65a0a4f600998cbbaa50157c6d89dfec3c758409513c4db16af7908daa7e9cab'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186201-186212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186201-186212.nc' 'SHA256' 'db4f5168e0945be8b9b114c32bc4eb2d13ff4516eb7cd7e3f187c59186ae3559'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186301-186312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186301-186312.nc' 'SHA256' '27edfe0cf4025782a59f31c2eea1992a3e16efea28367ca594bb59e7942a5e63'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189401-189412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189401-189412.nc' 'SHA256' '755626046863c53771b363330307775377ef8415cfe008e16feb697f8d3c51b9'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193201-193212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193201-193212.nc' 'SHA256' '48de32c09e6e49da083897e995a66c6624120c2d0f1f472dae078868c514c3d5'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194801-194812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194801-194812.nc' 'SHA256' '824e02c6190f59f29c73f2f68a20f516b601485732b077ef54f4aa4c52d1e051'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195601-195612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195601-195612.nc' 'SHA256' 'a41de4554a42cb48bdb723f27109585e6fe6b339c0b9ba4f2ad39d33b3ae1461'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_201001-201012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_201001-201012.nc' 'SHA256' '8f602838683f63997ac5ede963f896c8b04b77b88584cbd9e0b85eae40400233'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188901-188912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188901-188912.nc' 'SHA256' '1972c7d3b1bf200f8e12739d4c66fe46ca7134774bc96c9d3e8d05d207551e13'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189701-189712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189701-189712.nc' 'SHA256' 'cd51ad9fefe1fa3725c8d3cebb3f0dfb945fddc40d7062b0dac63e95dd61ec50'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189801-189812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189801-189812.nc' 'SHA256' 'af84dd41ea5abf3019989e163a89e2b1ffe21184f5d88f753880656adc2f981d'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192601-192612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192601-192612.nc' 'SHA256' 'bf9a092090da4502b3aa6f87b512d84f710f5e59c348ef60c84acbc5215b27a2'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193601-193612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193601-193612.nc' 'SHA256' 'b386d4034792413a3dadb1c18a134459b353489769c55c79c2e7d0fa1d2e4522'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195801-195812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195801-195812.nc' 'SHA256' 'ef4399c390fdf39ecd4361437f6d63aef74d5a7c57435729ebba4e9b7fe8d0e7'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200401-200412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200401-200412.nc' 'SHA256' '55b55e638a57ea73d93208ed98a4dd098940ba922a3883214406a8ee239fcfc0'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200901-200912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200901-200912.nc' 'SHA256' '15aa609181221594075128b3f8a1675c4415636829d009a5df472b0db6128008'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186401-186412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186401-186412.nc' 'SHA256' '2da770075e5910ee613fea01b3a36208034e839d9fd70e3412a7a496c9e4799e'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189601-189612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189601-189612.nc' 'SHA256' '7b0127dc0983844e5470176bc1a7c9c4fca5d6a4cd3e3ac25b2f3159cbde2488'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191101-191112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191101-191112.nc' 'SHA256' '5b62e776cb254410608d8ffeb6b03d8dd3b1f3b193e1fb534dc50e5129b9eb7a'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197801-197812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197801-197812.nc' 'SHA256' 'b572618d90506ebd09d388118c9537050bcb9ac7b23c0fcfdb18cf461ab313aa'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198301-198312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198301-198312.nc' 'SHA256' '5ac1a9aa58afb3bb3cf09e59af3a8f970e5c190733f0c63c48034f30edca5370'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199701-199712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199701-199712.nc' 'SHA256' '69bf80e53523eb1a16a6935ed6cb7a050d9dc6f4dea5dfa29b48e00b5d2a5614'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199901-199912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199901-199912.nc' 'SHA256' 'ac326ea9daac77d705f6842e4b9bd3c9893835d0bcda158c82bed39e9213358f'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186001-186012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186001-186012.nc' 'SHA256' 'cf7703dfe9d87edbe6f2b319bf56622e074d9b893805d026ba4fe9594b5040a8'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186501-186512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186501-186512.nc' 'SHA256' '3a61be4d6d7ef694e586471dc753fa373fdb9d70fbc8581e4e7a17c3f410da9c'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186801-186812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186801-186812.nc' 'SHA256' '645dba10f00099699f8902c70c83e6d7f06912095d09763e83753cd1615c96cb'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187001-187012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187001-187012.nc' 'SHA256' 'd1611bae17ffa0826ce61d7c81c181737ddcb53c0036ce7eaa47b5b10369c762'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192901-192912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192901-192912.nc' 'SHA256' '25e28119fe5e1b266a082fc6502f1db4b27e35239ff748c556e527d2722ae8c7'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193001-193012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193001-193012.nc' 'SHA256' 'f9c754874b7a973a36e5767b494c81cc2e582a564fd850ed5a4db3779d199f2b'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195201-195212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195201-195212.nc' 'SHA256' '546666419881c08cc7430d42a038f1db07de4e4859f4d262aa5b6f12b217a553'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196901-196912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196901-196912.nc' 'SHA256' 'fa31980a623afc4b1f8d5c27d6277cd2d3af972c757b6266edd2057fb0f8dc45'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199301-199312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199301-199312.nc' 'SHA256' '2c079c64abbe512618de0a4373c163495f9f1ebaa2e2710ec278aab632928d04'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_201301-201312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_201301-201312.nc' 'SHA256' '1e332fdf3497f1aae4d31969a4c66529dee551cc741623a1195f6949926a86e8'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185801-185812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185801-185812.nc' 'SHA256' '8c697ca89cb6cfdc1a85797b7bf3739deaaabc387cf44265e2d3f779eca179e8'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186701-186712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186701-186712.nc' 'SHA256' '22f762140963ba44b8ceed0bc8998fdad65ce04df4e9a8907034d2e642c1c56d'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187101-187112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187101-187112.nc' 'SHA256' '01e00bc3ad2bd97bb842e880d1474afd75e9210464a1faf91e5fb99cdacac632'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187601-187612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187601-187612.nc' 'SHA256' '26365f0f47fd1111da3028e7704b8be23934f192872d8d70d8f06df7ef76567a'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188201-188212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188201-188212.nc' 'SHA256' 'e645fb5ebf7ccd3134d53ead8be6f11c5d436859cb5f3482ac2f73bb07496854'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189101-189112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189101-189112.nc' 'SHA256' '090c8db198508d77b8ec784be7a9b6867ae7542671f55262a4b0cf8058da7d16'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189901-189912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189901-189912.nc' 'SHA256' '4334e20bbd02983d38de1454e9928f90a73d9fbd16917ca0ee668bd1b83d42fe'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190501-190512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190501-190512.nc' 'SHA256' '0046a88e37816976b9a958767b92f98b114edba775e8d8d90e5387d28e319769'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196001-196012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196001-196012.nc' 'SHA256' 'fa8d8c6307d9e1a7595c2785dc8540930aa64342010c631f3a3fac12f53c8d11'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197201-197212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197201-197212.nc' 'SHA256' 'c4f8bf211d8da0829b42a410eb7b82ef8bfd5f4778cbf5bfc5699c1b63f2b401'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198601-198612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198601-198612.nc' 'SHA256' '56d959fa3fd8fed1d2183f9d34fdbcb63f00c6cd7ce84a1152dc20d01d808fdd'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199101-199112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199101-199112.nc' 'SHA256' '92e84f95f4e5834e623f840e12fad9eb89b16616abf3314a09671808b8821ba8'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_201201-201212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_201201-201212.nc' 'SHA256' '2d58a5f0bf3c947e8607e6ab656fb1ee35e1686d20e584a948c332db752aeacf'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_184912-185012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_184912-185012.nc' 'SHA256' 'bfa9fc5dc0ac87cae1d9c907bd19a441a76b1e0b3aa18a90f5016571cfd43df0'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185201-185212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185201-185212.nc' 'SHA256' 'd3662a588e776fdacd4d860a70afe7b1da0a9c3b2bb8cf6dcffb89aeb3678926'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186601-186612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_186601-186612.nc' 'SHA256' 'c1a01afab6cf8f5d7dc268a09ca528c9ce62029b5b04811281add5c28e8e39c6'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187701-187712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187701-187712.nc' 'SHA256' '2502768cce0855b0fe8b63d71d1bae30d36ce8ccfbbeadaa3b972ae68dc54cc2'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188001-188012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188001-188012.nc' 'SHA256' 'a766c793d92f0a1d6874b7205fd55cf6b3f807b3332253d9c2ea16109dd11485'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188301-188312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188301-188312.nc' 'SHA256' '6eece904025284e759a09a8ea71d49a5d5551c590250a1b1a8164755c90347b1'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189001-189012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189001-189012.nc' 'SHA256' '37167cdb8a815e7cc0302f6a9895b4bca688d36e98cf5cb8e4d66a154c5e1d12'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196201-196212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196201-196212.nc' 'SHA256' 'd4ac6b5cd8decb967e3eb671bd8744215214bc4695fe3dfd3bfc1be588b3e518'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196801-196812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196801-196812.nc' 'SHA256' '897cbb8bf331e420d17d5dea4afb888ee9d4dcdd2104770fff874ee32ecc2706'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188101-188112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188101-188112.nc' 'SHA256' 'cfac3bee419fabdfd772558ae91f5dbeb8bba9a77dce768d8b402b8d4fda12a7'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189301-189312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189301-189312.nc' 'SHA256' '5e0c73e21eee6c165ec058ba15bea42e6cbd81a0d74680148fe9f3d0168eead4'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190001-190012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190001-190012.nc' 'SHA256' 'fc62668926f18bdb58ecb57097475f7a4698250741cdf84efb4d47362eebfa6b'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190601-190612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190601-190612.nc' 'SHA256' 'de93af62ffae4f0f6bcefd12a101357be51a08d040e868e1c5af782bb9fefba3'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190901-190912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_190901-190912.nc' 'SHA256' '8c8d2140f8a98b7e0cd131cd31be7197332cd7d5e6395e278fc732ecbd513377'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196101-196112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196101-196112.nc' 'SHA256' '63b71b1dc156404c8b925b2a9a3f6ec94d5951e623b0cbc40f14fa25535d987e'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198801-198812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198801-198812.nc' 'SHA256' '8b44cf1305f46e060bcfc25fd81bb9bfb6af79681dc32cedca894ff1b88d65ad'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198901-198912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198901-198912.nc' 'SHA256' 'aa1c92931ff8533a0fdcdb63540665aaa115cbe4c9d967ed277ff64e76c5a7f0'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200601-200612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_200601-200612.nc' 'SHA256' '6f0e95e913b7d83bacc3a8a2c7e341701c28a48bd3c878128043d2ce9e8d7dea'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_201101-201112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_201101-201112.nc' 'SHA256' 'b76281aefa4d5e9251f50118d307a232a9a0cccdd20ef8d133aa3b3102b538e4'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185401-185412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185401-185412.nc' 'SHA256' '6d514e909d4381a108b60933639260b18fbc27c73c1f2736a11e1bd9995c2fd3'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187501-187512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187501-187512.nc' 'SHA256' 'e307daf88c09bdb8243ecf05860ff1248a3e6c57e94b6e39e6a33ac79663f381'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187901-187912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187901-187912.nc' 'SHA256' '933e77b8d876fc4a67e063bf9bb7dfd40d641df353c2a91a65a25148ed546ad6'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191201-191212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191201-191212.nc' 'SHA256' '877e9fafe3b1282f04e04898d40142b2eb3f90a6fa6c72867d9df6eb5bace318'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191401-191412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191401-191412.nc' 'SHA256' 'e0c0ae4c0c63082cf9c33006c9f9f698d2227cd9f1e50064734bb4322316bae0'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191701-191712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191701-191712.nc' 'SHA256' '0b271e5b81b525683a786655922fcfd8c79fb1f33a86bbba771b00c4cb336cb2'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192301-192312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192301-192312.nc' 'SHA256' '5e99fd1da948c316a848b1aa3574091f67a54098e6b28316bffb2503eefbf67b'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193401-193412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193401-193412.nc' 'SHA256' 'bcaea1e02787acb03a0fbf06873dd28726dc0c29eff877243d25ca75f57a8e55'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193501-193512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193501-193512.nc' 'SHA256' 'c9e53fcfe9cf8d8836daf020745aeb95fe089b02deb7084ddb80edae394c4539'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194001-194012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194001-194012.nc' 'SHA256' '167aed8a75f05c1d19e9e54117bee8eaad6e300e75ec83fb041b2a9ed1aad21f'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194401-194412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194401-194412.nc' 'SHA256' 'f43beb516e300d8049f6dbdd4182616ec061805bb9b483b171adf2c3ea73a205'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195501-195512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195501-195512.nc' 'SHA256' 'be07c42424e50bd529754b97518060c79a6c233e3e065edc888cf79a0c0f836f'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197101-197112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197101-197112.nc' 'SHA256' 'fe09e47010c95c8970fcea6afb92555d5620affd63cf84e57344205e666494cd'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198101-198112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198101-198112.nc' 'SHA256' 'c75e1515601e976679422f9bbbb24a8d0a28603356e73ede387365a598422fb6'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198501-198512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198501-198512.nc' 'SHA256' '75e660de3230a0fdaa822314dfe51d80d78ec2cf682e41b309813b02947a5b24'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199601-199612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199601-199612.nc' 'SHA256' '74741fc1508b2a5173c050de6aadaebe8d015313065176a354323866645e7d38'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185101-185112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185101-185112.nc' 'SHA256' '3ae63a74246fb759054ab200deed0e4986bc5d5a6ea4d319c6e6cf802d1afffb'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185601-185612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185601-185612.nc' 'SHA256' '4deb25b73c60225a96fc324ab8d81eec94a93c7fc654a191c962883b5fc10795'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188401-188412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188401-188412.nc' 'SHA256' '888181d9ccc9858cb949b59d1f50d79f91e73d1f510e4d7beffba50d98694203'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188701-188712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188701-188712.nc' 'SHA256' '06e608b80ce2e8b57c3c1951c1990852ad3477e251112f9f0903f6f9763443f2'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191301-191312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191301-191312.nc' 'SHA256' 'e7dd8fbfe73b0427e0b5b6e81381969cc4c05c2de20ed54e315955cdf34b46c9'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192401-192412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192401-192412.nc' 'SHA256' '5deff5945e70b477163b324126ea9f7a45dcdfd8310188eeebc3c4541dcc7fbe'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193801-193812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_193801-193812.nc' 'SHA256' 'aeeff3e3ffcccff6a4164062eb474e286fd28bd0c223003cb86e41beae6533c9'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194301-194312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_194301-194312.nc' 'SHA256' '5e8b6952e5e123f878840e207f5ed087ce5e7ee6108d873b12a715599cf798d6'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197601-197612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197601-197612.nc' 'SHA256' '1c4915dbc976fd64e6f676cbaa12fb7817c3546b1e7c156b1bad5a21a8b37cc0'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198701-198712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198701-198712.nc' 'SHA256' 'c03694f2849adb3ff4cd109db92d01f82304ce8eaedf6b5721e8b5c8ab2dbe22'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199501-199512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199501-199512.nc' 'SHA256' '46b92512efaca4056dcca1cdf2447bd141eb8ff1a50a101fd4751a45e4d62605'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_201401-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_201401-201412.nc' 'SHA256' 'a391d88175309a50757ff9c2fe71f63ef99a47884d31b3b4b4da06ccec47710a'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187201-187212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_187201-187212.nc' 'SHA256' 'f294178f93b5114eb80e903f0a8d73d355ff62c0a5a2c3f1d4bc534e28170ac8'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188601-188612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188601-188612.nc' 'SHA256' '88a9ef57e01f227b9fd75719bc0b3c8c3ec9d6c4f93e7c8d6e2489955b90858f'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188801-188812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_188801-188812.nc' 'SHA256' '38c97801efda1d6fa737ae825fd517be480a9d23a2ff7c71ebf9d3f6cf5bef70'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189201-189212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_189201-189212.nc' 'SHA256' '742c61fe0a8934978707911eeb35e0f0573588defdfa094140b85126f85339f2'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191801-191812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_191801-191812.nc' 'SHA256' 'd5ddf04b0f7fd05b89c5b9f263aebd676f2f0eb9b41919fab748c3091f81a89b'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192501-192512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_192501-192512.nc' 'SHA256' '15fa0de5301256faf674954a41fd70e02d6f8d8438eb0e1d380ea9b0fba80a0c'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195701-195712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_195701-195712.nc' 'SHA256' '5d8ff052d3c45a3b73f911bc3760204733476122c2eec9209440d7b5b2d3733c'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196601-196612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_196601-196612.nc' 'SHA256' '5b9305bb42187649452337776d94046e7ad3ea616a50071958b29504b9764cb8'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197301-197312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197301-197312.nc' 'SHA256' '5044201a9711abd871090faa037a10eac4db8926f20cde17c97a83ab35cd9d51'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197401-197412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197401-197412.nc' 'SHA256' 'a92ee4a8723695bdf7fce4685e7c632cac7350675a30ed74d26e518a3d618bb1'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197501-197512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197501-197512.nc' 'SHA256' 'ceddfff0913ff061377fd20a20d64581634347531b6338c3bbaa06fd42a1b246'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197901-197912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_197901-197912.nc' 'SHA256' '7cefb42112912e89dd33ea06b4b6cbf807cb1e60ea12a2a5fcec908e91feb808'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198001-198012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_198001-198012.nc' 'SHA256' '7ba2dfedcc315f9879e0e58e3cf2ad821e4deb2b4d243a63f52724d30c78129e'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199401-199412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199401-199412.nc' 'SHA256' '76ca255aae3ad2176da354acded49f51bd2b46b272984af23e312b7d4cc0e93c'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199801-199812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_199801-199812.nc' 'SHA256' 'b2cd9c18721cf6f84d6afb83b306aab63a639ef4acc7987e72a3dbda911ca3f0'
'prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185301-185312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r15i1p1f1/Amon/prw/gr/v20200201/prw_Amon_EC-Earth3_historical_r15i1p1f1_gr_185301-185312.nc' 'SHA256' '2fe17b683e06138e9d0915b5723a8b9b49c834c94ec02628e7a4e178c1deb759'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }  
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            unset failed
        fi
        
    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 165 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
